plugins {
    id 'com.android.application'
}

android {
    namespace 'tech.garhy.gtbybit'
    compileSdk 35

    defaultConfig {
        applicationId 'tech.garhy.gtbybit'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.0.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
    }
}
